swagger: '2.0'
info:
  title: Open edX API
  description: APIs for access to Open edX information
  contact:
    email: oscm@edx.org
  version: v1
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  
